### ISSUE TITLE
Clarify usage of depreciated permissions

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/bluexp-setup-admin#107]
Page: [Google Cloud permissions for the Connector](https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-permissions-gcp.html)

On this page (and other pages references the APIs/permission used by the Cloud Manager Connector Service Account in GCP)

The following two permissions/API calls are listed:
```
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
```

Google depreciated and shut down the composite types feature on February 22, 2022.  Can these two permissions/APIs be confirmed as no longer being required, and then have the documentation updated to reflect this?

**Comment by netapp-bcammett** [comment]
Mike,

I've reached out to the product team. I'll let you know what I hear.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
There's an open item in the upcoming sprint to validate all Google Cloud permissions required for the Connector. That will include these two permissions that you called out. We'll update the docs based on the testing results.

**Comment by ntap-bmegan** [comment]
@netapp-bcammett - What is the status of this issue?

**Comment by netapp-bcammett** [comment]
We're waiting on input from the engineering team. I will update this issue when I have details to share.

**Comment by netapp-bcammett** [comment]
Mike,

There are no changes that we can make to the documentation at this time. Engineering analysis and subsequent updates to the BlueXP generated policy is required.

An issue is open with the engineering team to verify Google Cloud permissions for the Connector. We will update the documentation when the engineering work is complete. I can send you a link to this internal issue if you'd like.

Thanks,
Ben
