### ISSUE TITLE
AWS permissions for the Connector page is missing KMS permissions

### ISSUE THREAD

**Issue by alexander-gebhardt** [NetAppDocs/bluexp-setup-admin#166]
Page: [AWS permissions for the Connector](https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-permissions-aws.html)

The permission list/policy is missing the `kms:GenerateDataKeyWithoutPlaintext` permission which is needed when creating a second aggregate on an existing CVO cluster. The permission can be scoped to the KMS key that is used to encrypt the EBS volume. In this specific case a customer managed key was used to encrypt the EBS volumes.

After adding the following statement to the policy the aggregate creation succeeded. Please note that the KMS Key ARN was replaced with a placeholder

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "kms:GenerateDataKeyWithoutPlaintext"
      ],
      "Resource": "volume-encryption-key-arn",
      "Effect": "Allow",
      "Sid": "cvoVolumeEncryptionKey"
    }
  ]
}
```

Screenshot CloudTrail
![image](https://user-images.githubusercontent.com/76949337/224982736-45195011-9c9f-4c28-aba5-c94676505c59.png)

Screenshot BlueXP
![image](https://user-images.githubusercontent.com/76949337/224982943-9492ff82-67c5-4adb-81c5-2e6b673a5c94.png)

**Comment by alexander-gebhardt** [comment]
Hi @netapp-bcammett,

in my case the key is in the same account as the Connector and the CVO

Best,
Alex

**Comment by netapp-bcammett** [comment]
Was the AWS KMS set up for Cloud Volumes ONTAP as described on this page?
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-setting-up-kms.html

Thanks,
Ben

**Comment by alexander-gebhardt** [comment]
It appears the described setup was not done.
The doc you linked describes adding the BlueXP IAM user in the key policy. In my setup I observed the API call to KMS coming from the instance profile of the Connector though.
Since the KMS setup is described though I guess this issue can be closed

**Comment by netapp-bcammett** [comment]
@alexander-gebhardt,

I spoke with someone from the product team about the `kms:GenerateDataKeyWithoutPlaintext` permission. I'll provide an update on whether it should be included in the Connector policy.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
kms:GenerateDataKeyWithoutPlaintext was added to the docs and should be available tomorrow in the policy that BlueXP generates for the Connector.

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-aws.html

Thanks again,
Ben
