### ISSUE TITLE
This is not the Azure Manual Install

### ISSUE THREAD

**Issue by saschape** [NetAppDocs/bluexp-setup-admin#207]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-azure.html

### Page title

Create a Connector in Azure

### Summary

Please check Doc page, looks like the manual walk through for AWS.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
I did remove the information about the awscli from the page. It was previously included on all manual installations, but it's no longer included. I don't see any other information about AWS on this page. I'm going to close out this issue.

Thanks again,
Ben
