### ISSUE TITLE
We no longer need all these backup permissions

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/bluexp-setup-admin#217]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-aws.html

### Page title

AWS permissions for the Connector

### Summary

In the Cloud Backup permissions and descriptions: https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-aws.html#backup-and-recovery
Please note that the first section that has ec2:StartInstances   through cloudformation:DescribeStacks, this was needed when we had a separate VM that was deployed to do singe file restore.
With our newer updated architecture, this functionality is containerized in the connector VM, so we no longer need to launch a VM that way.
This is causing customer confusion.
I think we should be able to remove all of those from the doc, they are not listed on the Backup pages.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@nichollri,

I removed the list from the section in the docs that describes how we use the permissions. However, the product team needs to update the policy itself. This will require internal follow ups with engineering.

cc: @netapp-tonacki
