### ISSUE TITLE
Please add connector reboot steps

### ISSUE THREAD

**Issue by virtualhawk** [NetAppDocs/bluexp-setup-admin#229]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-managing-connectors.html

### Page title

Manage existing Connectors

### Summary

Please add the proper connector reboot steps to this page.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Hi David,

Are you looking for more detail than what's currently listed on the page under Operating system and VM maintenance?

> If you need to stop and then start the Connector VM, you should do so from your cloud provider’s console or by using the standard procedures for on-premises management.

Thanks,
Ben

**Comment by virtualhawk** [comment]
Hi Ben,

      I looked right over that sentence!  Thank you for the quick reply!
