### ISSUE TITLE
Add a troubleshooting section / do you not see subscription in Digital Wallet

### ISSUE THREAD

**Issue by mgraws** [NetAppDocs/bluexp-setup-admin#230]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-aws-accounts.html

### Page title

Manage AWS credentials and subscriptions for BlueXP

### Summary

Hello,

The short video is great for helping customers understand what to do for associating a subscription.  I find that I share the 20 second mark on for most customers as a side note.

Can we add a troubleshooting section for when a customer doesn't follow the re-direct and save the sub in BlueXP?  Basically check digital wallet do you see the sub?  If not follow these steps (ideally with pictures)

To activate or try activating again they can follow these steps.
1.	Log into AWS Console and go to Marketplace Subscriptions
2.	 (insert picture)
3.	Find the new subscription they signed up for (example below)
4. (Insert picture)
 
5.	Click Set up product.
6.	This will open a link to the offer page.
7.	There will be a link set up product
8.	This routes to the BlueXP log in. Log in.
9.	Follow the wizard all the way through to add subscription.
10.	Make sure the proper subscription is associated.  (see other email)
11.	Refer to this video.  Relevant content is 20 seconds and after
	https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-aws-accounts.html#subscribe]

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@mgraws,

Thank you for submitting this feedback. I'll start working on this soon and will let you know if I have any questions.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
@mgraws,

Can you please let me know what you mean by this step, specifically the part about the email?

> Make sure the proper subscription is associated. (see other email)

**Comment by mgraws** [comment]
Yes, sorry for the confusion.

I wrote those steps out for a customer and in a previous communication I sent an email with checking credentials.  This was the information as part of that step and the "see other email" piece.
_________________________
Extra detail on step 6
Customers should see the latest subscription under Digital Wallet Subscriptions.  They can then check which subscription is currently associated by going to the Account Credentials tab and clicking view.
https://console.bluexp.netapp.com/credentials/account-credentials<https://urldefense.com/v3/__https:/console.bluexp.netapp.com/credentials/account-credentials__;!!F8-Dj6fVkZI!bAg_kOcXu3CPzvAZOlZwYt7C92vHHUmoUDYanaioSsTbnuVBiWpzgsFkpKzehvVKpOVY_bgGDsBD8oBQvOLpRiijiA$>
If for some reason the old subscription is still associated you can follow these steps to associate the new one: https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-aws-accounts.html#subscribe




Matthew Robins
AWS Ecosystem SA

NetApp
+1 914.318.2629 Mobile Phone
***@***.******@***.***>

**Comment by netapp-bcammett** [comment]
The updated has been published:
https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-aws-accounts.html#associate-an-existing-subscription-with-your-account

Thanks again!
