### ISSUE TITLE
Seeing endpoints specified for public cloud in the Private mode connector setup link

### ISSUE THREAD

**Issue by chuffster80** [NetAppDocs/bluexp-setup-admin#232]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html

### Page title

Prepare for deployment in private mode

### Summary

hey team,

Working on a support case.
Wanted to bring to your attention and verify if this section is supposed to be in the Private Mode setup about endpoints.
With the page referencing dark site installs, do we not restrict connectivity to endpoints?
Verifying if they were added on this page by mistake since the line mentions "The Connector contacts the following endpoints to manage resources and processes within your public cloud environment."

-Chris

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by chuffster80** [comment]
so even in private mode we still need some type of connectivity using endpoints when CVO is involved

**Comment by netapp-bcammett** [comment]
Yes, connectivity is required to the cloud provider endpoints, but there's no connectivity to the BlueXP SaaS layer or any other netapp.com endpoints.

**Comment by chuffster80** [comment]
thanks Ben, all good here to close

**Comment by chuffster80** [comment]
thanks Ben all good to close
