### ISSUE TITLE
Isolated links should not have terminal punctuation

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/bluexp-setup-admin#239]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-managing-netapp-accounts.html

### Page title

Manage your BlueXP account

### Summary

![image](https://github.com/NetAppDocs/bluexp-setup-admin/assets/56453501/85b56f3c-cf48-4f57-a359-eeebe46ba75a)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@ntap-bmegan,

Our content standards don't say that isolated links should not have terminal punctuation. In fact, one of the examples in our standards is formatted just like the link shown on this page.

If you think that we should adjust our standards, then please open an issue against the content standards.

Thanks,
Ben
