### ISSUE TITLE
System registration info needs an entry to be added for CVO/CVO-HA support registration to reduce ambiguity.

### ISSUE THREAD

**Issue by moe52180** [NetAppDocs/bluexp-setup-admin#259]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-user-roles.html

### Page title

Roles

### Summary

System registration info needs an entry to be added for CVO/CVO-HA support registration to reduce ambiguity. It is unclear which of the 3 options shown here allow or deny user ability to register CVO systems.

![image](https://github.com/NetAppDocs/bluexp-setup-admin/assets/143653645/e257eebf-f59b-478b-9672-4dd2516f21a8)

I had a customer trying to figure out why he and a peer could not register, but their team lead could register CVO. The lead has a role of Account Admin but the other 2 are listed with the Workspace Admin role. It is not clear for registration which role has the authority to register their CVO. 

Please update the documentation.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@moe52180, thank you for submitting this feedback. I just wanted to confirm that you're talking about the following option, which enables support registration for an individual Cloud Volumes ONTAP PAYGO system:

![image](https://github.com/NetAppDocs/bluexp-setup-admin/assets/18287750/47ee5d60-7b65-4211-99b7-5d30d7987862)

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Hi @moe52180, I just wanted to follow up on my previous question. Thanks!

**Comment by netapp-bcammett** [comment]
@moe52180, the other support registration option is for the BlueXP account from Help > Support, so I just wanted to clarify which support registration you were talking about.

![image](https://github.com/NetAppDocs/bluexp-setup-admin/assets/18287750/ce378a1f-d5f1-4c18-aa31-63c5a2c53e69)

**Comment by netapp-bcammett** [comment]
I was assured by our engineering team that both the Account Admin and Workspace Admin can register Cloud Volumes ONTAP working environments for support. That's covered in the page that you referenced under "Manage working environments."

In the most recent release, three bugs were fixed related to support registration. It could be that your customer was hitting one of these bugs. 

If the issue occurs again, I would suggest opening a support ticket.

Thanks,
Ben
