### ISSUE TITLE
Multiple connectors issue with working environments

### ISSUE THREAD

**Issue by rayb-netapp** [NetAppDocs/bluexp-setup-admin#260]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html

### Page title

Learn about Connectors

### Summary

There needs to be an explanation that a working environment should only exist on a single connector.  Especially with multiple connectors.  Also need to take care when in a fail over situation, on the fail back the working environment is removed.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Hi Ray,

Thank you for submitting this doc update request. Can you please clarify what you mean by "a working environment should only exists on a single connector."

As described in the following section, my understanding is that you can discover a working environment from multiple Connectors for disaster recovery purposes:
https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#disaster-recovery

Thanks,
Ben

**Comment by rayb-netapp** [comment]
When a working environment is in 2 or more connectors and there is an issue with the connector not communicating with our license server or the connector is on a dark site, there is an issue with expired licenses shutting down the CVO nodes.

**Comment by netapp-bcammett** [comment]
Based on the response from the engineering team, we still support managing a working environment with multiple Connectors.

As mentioned in email, please open a feature enhancement for this specific scenario.
