### ISSUE TITLE
The [Configure storage] step needs to improved for more info

### ISSUE THREAD

**Issue by Xinwei-Wang** [NetAppDocs/bluexp-setup-admin#266]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-marketplace.html

### Page title

Create a Connector from the AWS Marketplace

### Summary

A customer is confused if they can set the AWS KMS key when deploying the connector from AWS marketplace as below doc:

https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-marketplace.html#step-4-create-the-connector
**Configure storage: Keep the default storage options.**

it should no doubt that customer can set their storage by clicking the advanced setting as below I created kb, since when deploying from BlueXP, we offered customers to choose enable or disable encryption and also can choose kms key.

https://kb.netapp.com/Cloud/BlueXP/Cloud_Manager/How_to_set_AWS_KMS_key_when_deploying_a_connector_from_AWS_marketplace%3F

So , my request is , please add an additional description under  the below sentence,  like " if you want set AWS KMS key, click the advanced button to enable the encryption and choose the proper KMS key as needed"
**Configure storage: Keep the default storage options.**

Thanks
Edwin.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@Xinwei-Wang, thank you for letting me know. I updated the docs to include this information.

![image](https://github.com/NetAppDocs/bluexp-setup-admin/assets/18287750/7dee9eb2-014e-4eb6-a874-da38bf0352b1)

Thanks again,
Ben
