### ISSUE TITLE
Removal of AWS permission: "kms:ReEncrypt*"

### ISSUE THREAD

**Issue by wilshields** [NetAppDocs/bluexp-setup-admin#269]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-aws.html

### Page title

AWS permissions for the Connector

### Summary

Can we remove the requirement for: "kms:ReEncrypt*" from ALL AWS IAM Policies?

The documentation is incorrect. This is never used by BXP/Connector as it does not support key rotation and that is the only purpose of that permission. I have verified deployments work fine without it.

https://docs.aws.amazon.com/kms/latest/APIReference/API_ReEncrypt.html 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
No doc changes needed for now as the policy in the docs matches what's in the policy generated by BlueXP. We'll make any updates after we hear from the engineering team.
