### ISSUE TITLE
Additional public endpoints

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/bluexp-setup-admin#270]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-azure-bluexp.html

### Page title

Create a Connector in Azure from BlueXP

### Summary

Hi,

it seems that FW such as CloudGuard identify also additional endpoints that are behind the URLs listed in the docs.

E.g.:
- support-hio.netapp.com (216.240.21.18)
- Azure Front Door Public (13.107.213.45)
- ec2-35-172-26-84.compute-1.amazonaws.com (35.172.26.84)

Are this static endpoints that could be added to the whilelist? 

Thx
Holger

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Thanks @kholger. Sent you an email for further clarification.

**Comment by netapp-bcammett** [comment]
As discussed, we added the following statement before the list of endpoints for the Connector:

Note that the endpoints listed below are all CNAME entries.

Thanks again,
Ben
