### ISSUE TITLE
Restricted Mode: API Endpoint

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/bluexp-setup-admin#273]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html

### Page title

Learn about BlueXP deployment modes

### Summary

Hi,

The table shows "The BlueXP SaaS layer" as API endpoint for restricted mode accounts.

1. When trying to use Terraform provider on a restricted account, there is an error message saying that this is not allowed for this account.
2. Using the SaaS endpoint for restricted accounts would contradict the user's ability to protect their connector from unauthorized access.

Could you please check and verify if it's really the SaaS layer API endpoint or just the local endpoint for restricted accounts.

Thx
Holger

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@kholger, thanks as always for providing your feedback. I will confirm with the product team and get back to you.

**Comment by netapp-bcammett** [comment]
I updated the table to show the Connector as the API endpoint for restricted mode accounts.

Thanks again,
Ben
