### ISSUE TITLE
Restricted mode deployment account issue

### ISSUE THREAD

**Issue by finnian345** [NetAppDocs/bluexp-setup-admin#274]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-restricted-mode.html

### Page title

Deploy the Connector in restricted mode

### Summary

Hello Team, there may be an issue in this documentation with Step 2. 

This is the step where the option for restricted mode appears. However, it says two things which are a bit conflicting. 

The first warning under the title: "_If you already have an account and you want to create another one, then you need to use the Tenancy API. [Learn how to create an additional BlueXP account](https://docs.netapp.com/us-en/bluexp-setup-admin/task-create-account.html)_." 
- This warning notes that you can create a restricted BlueXP connector with a new account using Tenancy API which would mean there is an existing organization. 

However, under Step 2 > 3d, the line: "_Note that you can’t change this setting after BlueXP creates the account. You can’t enable restricted mode later and you can’t disable it later._"
- It appears that if you try a new account/email under an organization that is already used in other BlueXP connectors, then enabling restricted mode is not possible. 

I'll be noting this in a KB as well if you think that that is a more relevant place for this information, but I think this information could be more clear on what is required for existing users to create a restricted mode BlueXP connector. 

Thanks a lot,
Finnian O'Neill

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Hi @finnian345, thank you for submitting this issue.

The statement about using the API to create another BlueXP account is talking about the BlueXP account where your users, workspaces, and Connectors reside.

I'm not sure what you mean here:

> It appears that if you try a new account/email under an organization that is already used in other BlueXP connectors, then enabling restricted mode is not possible.

If it's a new BlueXP account, how would it already be used with other BlueXP Connectors?

Thanks,
Ben

**Comment by finnian345** [comment]
Hello Ben,

From testing by Jerome Blanchet SE, he found that creating a new BlueXP
account still did not allow him to enable restricted mode on the new
connector, and the option was simply unavailable.

Only creating a new organisation and then a new account worked for him and
his customer.

Maybe I am wrong however but the description in the documentation don't
align with this experience.

Thanks a lot,
Finnian

**Comment by netapp-bcammett** [comment]
Finnian,

Can you please explain what you mean by "organization"? What is that and how was it created?

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
After confirming with the product team, the following was added to the documentation.

> Before you begin
> 
> The person who sets up the BlueXP Connector must log in to BlueXP using a login that doesn't belong to a BlueXP organization that is operating in standard mode.
> 
> If your BlueXP login is associated with an organization that's operating in standard mode, you'll need to sign up with a new BlueXP login or NetApp Support Site credentials that don't belong to an organization. Otherwise, you won't see the option to enable restricted mode on the setup screen.

Thanks,
Ben
