### ISSUE TITLE
CLI script name doesn't match NSS download name

### ISSUE THREAD

**Issue by sbyosh** [NetAppDocs/bluexp-setup-admin#278]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html

### Page title

Install and set up a Connector on premises

### Summary

The CLI examples for running the script have a different name than what is downloaded from the NSS site.
ie. the docs have "OnCommandCloudManager-<version>" while the downloads have "Cloud-Manager-Connector-Cloud-<version>"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@sbyosh, thank you for letting me know. I just updated the docs to fix the installer name.

Thanks again,
Ben
