### ISSUE TITLE
Need to add mysupport.netapp.com to "Endpoints contacted from the Connector"

### ISSUE THREAD

**Issue by definitelynotsteve** [NetAppDocs/bluexp-setup-admin#280]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html

### Page title

Install and set up a Connector on premises

### Summary

This same endpoint may be needed for all installation types since support.netapp.com now redirects to mysupport.netapp.com

> GET / HTTP/1.1
> User-Agent: curl/7.29.0
**> Host: support.netapp.com**
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-Type: text/html
< Content-Length: 185
< Connection: keep-alive
< Date: Wed, 01 Nov 2023 15:53:48 GMT
< Location:
**https://mysupport.netapp.com/**
<
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@definitelynotsteve, thanks for submitting this issue. So it sounds like we should change this:

> https://support.netapp.com | To obtain licensing information and to send AutoSupport messages to NetApp support.

To this:

> https://mysupport.netapp.com | To obtain licensing information and to send AutoSupport messages to NetApp support.

Thanks,
Ben

**Comment by definitelynotsteve** [comment]
May be safer to require both, but I'd recommend validating w/ the related team(s) to be certain.

**Comment by netapp-bcammett** [comment]
The docs have been updated. Thanks again!
