### ISSUE TITLE
Missing "aiq.netapp.com" as required network endpoints from the "Prepare networking for using the BlueXP console" page.

### ISSUE THREAD

**Issue by kcantrel** [NetAppDocs/bluexp-setup-admin#288]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-networking-saas-console.html

### Page title

Prepare networking for using the BlueXP console

### Summary

If you don't allow access to aiq.netapp.com then if you attempt to go to the Digital Adviser page, it doesn't render correctly. Therefore, I think we should include https://aiq.netapp.com as a required endpoint.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@kcantrel, thank you for letting me know. I'll add it to the list.

**Comment by netapp-bcammett** [comment]
I added the endpoint to the docs:
https://docs.netapp.com/us-en/bluexp-setup-admin/reference-networking-saas-console.html

Thanks again,
Ben
