### ISSUE TITLE
Please confirm "Policy #1" of "Standard regions" on the "IAM Policy" section

### ISSUE THREAD

**Issue by yumiyaz** [NetAppDocs/bluexp-setup-admin#293]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-aws.html

### Page title

AWS permissions for the Connector

### Summary

I think "Policy #1" of "Standard regions" needs to add the following lines.

  ce:GetReservationUtilization
  ce:GetDimensionValues
  ce:GetCostAndUsage
  ce:GetTags

I checked the JSON of policy created by BlueXP.
It includes them.
Therefore I think a manual creation policy needs them too.

Could please confirm the engineering and revise the doc?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Hi @yumiyaz, thank you for contacting us. 

These permissions are not required for the Connector. There is a pending change from the engineering team to remove them from the policy that BlueXP creates. So no changes are needed in the documentation.

Thanks again for reaching out.

Regards,
Ben

**Comment by yumiyaz** [comment]
Hello Ben

Thank you for your support.
I understand.

Thanks,
Yuma
