### ISSUE TITLE
GCP Console Recommendation suggests reducing the BlueXP Connector VM type

### ISSUE THREAD

**Issue by stnadeem** [NetAppDocs/bluexp-setup-admin#302]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-limitations.html

### Page title

Known limitations

### Summary

As a recommendation, the GCP Compute Engine Console suggests reducing the VM to a lower VM instance type. 

This can result in errors on the BlueXP console. It is recommended to refrain from reducing the BlueXP instance type and always follow the requirements mentioned on this page:
[Manually install the Connector in Google Cloud
](https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-google-manual.html 
)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Thank you for submitting this feedback. I will take a look and update the documentation accordingly.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
I made a few updates to address this issue.

On the pages for creating a Connector from BlueXP, I noted that you shouldn't change to machine with less CPU or RAM. For example, from the AWS page:

> Creating the Connector from BlueXP deploys an EC2 instance in AWS using a default configuration. After you create the Connector, you should not change to a smaller EC2 instance type that has less CPU or RAM.

I also added a similar statement on the "Manage existing Connectors" page:

> *VM or instance type*
>
> If you created a Connector directly from BlueXP, BlueXP deployed a virtual machine instance in your cloud provider using a default configuration. After you create the Connector, you should not change to a smaller VM instance that has less CPU or RAM.
> 
> The CPU and RAM requirements are as follows:
> 
> *CPU*
> 4 cores or 4 vCPUs
> 
> *RAM*
> 14 GB

Thanks again for your feedback.

Regards,
Ben
