### ISSUE TITLE
External link content may have changed

### ISSUE THREAD

**Issue by dismn8r** [NetAppDocs/bluexp-setup-admin#311]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html#step-1-review-host-requirements

### Page title

Install and Setup a Connector on premises

### Summary

The contents of the external link "View Installation Instructions (https://docs.docker.com/engine/install/)" has possibly been updated. On the linked page there is no direct reference to installing docker on RHEL 7, which is currently the only flavour of RHEL we support installing the connector software on.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@dismn8r, I believe this is the correct link now:
https://docs.docker.com/engine/install/rhel/

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
As noted, https://docs.docker.com/engine/install/ contains a link to RHEL instructions.
