### ISSUE TITLE
Port 80 in inbound is needed for CVO image upgrades

### ISSUE THREAD

**Issue by melatsg** [NetAppDocs/bluexp-setup-admin#315]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-ports-gcp.html

### Page title

Connector firewall rules in Google Cloud

### Summary

Hello,

I would add in the purpose of the inbound port 80 the fact that it is needed for the image upgrade of the CVO. It needs to be opened from the CVO network.

Regards,

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Thank you for submitting this issue. We'll get that info added to the port list.

**Comment by netapp-bcammett** [comment]
The details have been added to the docs.

Thanks again,
Ben
