### ISSUE TITLE
Supported Docker Version until 25.05 outdated?

### ISSUE THREAD

**Issue by si-heger** [NetAppDocs/bluexp-setup-admin#328]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html

### Page title

Install and set up a Connector on premises

### Summary

The information on supported Docker Version until 25.05  may be outdated. When isntalling BlueXP-Connector Version 3.9.41 then theinstaller verifies the version and says that Docker 26.1.4 is ok.

So maybe documentation needs to be updated?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Hi Simon,

Thank you for reaching out. The documentation is correct: 25.0.5 is the maximum supported version of Docker Engine. The installer checks for the lowest supported version. It does not validate the currently installed version against the maximum supported version.

Regards,
Ben
