### ISSUE TITLE
Clarify use of /var and /opt

### ISSUE THREAD

**Issue by randobrando46** [NetAppDocs/bluexp-setup-admin#330]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html

### Page title

Install and set up a Connector on premises

### Summary

/var needs the specified amount of space because Docker or Podman are architected to create the containers within this directory.  Specifically they will create containers in /var/lib/containers/storage.  External mounts or symlinks will not work for this space.

/opt will be used to install /opt/application/netapp directory and it's contents

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@randobrando46, thank you for providing this feedback. I updated the docs with your suggested changes (I made a few editorial tweaks).

Thanks again,
Ben
