### ISSUE TITLE
Add clarification on NSS accounts using MFA

### ISSUE THREAD

**Issue by virtualhawk** [NetAppDocs/bluexp-setup-admin#339]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-sign-up-saas.html

### Page title

Sign up or log in to BlueXP

### Summary

Some partners and customers are unaware of NSS accounts using MFA/OTP and it would great to point out in our BlueXP documentation that NSS accounts use MFA by default.  And possibly point them to this KB for more information:  https://kb.netapp.com/Support/General_Support/FAQs_for_NetApp_adoption_of_MS_Azure_AD_B2C_for_login

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Thank you for submitting this feedback. I'll take a look and start working on the update.

**Comment by netapp-bcammett** [comment]
@virtualhawk,

I added the following under the description of the NSS login option:

> Note that the default password experience is a one-time passcode (OTP) to the registered email address. A new OTP is generated with each sign-in attempt.

I didn't point users to the KB for more information because I thought it might be potentially confusing that the page talks about support for identity federation, which is different than BlueXP's support for identity federation.

Thanks again,
Ben

**Comment by virtualhawk** [comment]
Hi Ben,

                Thank you so much for the update.  I heard some comments that NetApp partner's are telling customers that BlueXP does not support MFA (OTP being a part of MFA).  This should clarify that we support MFA with BlueXP NSS login.

David Hawkins
Cloud Solutions Architect, CVO Product Team
Mobile Phone: 330.892.7057
Need Help?  Please see our SharePoint<https://netapp.sharepoint.com/sites/CloudsolutionarchitectsGroup/SitePages/DetailedEngagementProcess.aspx>
