### ISSUE TITLE
Correct darksite uninstall command

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/bluexp-setup-admin#350]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-uninstall-connector.html

### Page title

Uninstall and remove the Connector

### Summary

The leading dot in the command to uninstall the private/darksite on this page's documentation needs to be removed.

The dot would only be needed if you were executing the cleanup.sh script without including the full path.

<img width="618" alt="image" src="https://github.com/user-attachments/assets/a7b2b72e-4cdc-468f-8bcd-d4338f58273b">

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@mimitche, thank you for letting me know. I removed the leading dot from the command.

As always, thank you!
