### ISSUE TITLE
Missing permission under CVO section

### ISSUE THREAD

**Issue by virtualhawk** [NetAppDocs/bluexp-setup-admin#352]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-azure.html

### Page title

Azure permissions for the Connector

### Summary

The custom role for BlueXP Operator is missing permissions under the section that explains the permissions for each data service.  The following permissions should be under CVO as it now supports VMSS in Azure (Custom role permissions section is updated already):

"Microsoft.Compute/virtualMachineScaleSets/write",
"Microsoft.Compute/virtualMachineScaleSets/read",
"Microsoft.Compute/virtualMachineScaleSets/delete"

Here is the link to the exact section: https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-azure.html#cloud-volumes-ontap.

Also, there is no "Change Log" section for the new permissions with explanation.

### Public issues must not contain sensitive information

- [ ] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Hi David,

I just sent you an email with details about these permissions.
