### ISSUE TITLE
Deploy the Connector in restricted mode screenshot of AMI is showing an old AMI that is either renamed or unavailable.

### ISSUE THREAD

**Issue by finnian345** [NetAppDocs/bluexp-setup-admin#356]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-restricted-mode.html

### Page title

Deploy the Connector in restricted mode

### Summary

Screenshot for the AMI shows 
![image](https://github.com/user-attachments/assets/f5df7b20-f356-4bb3-8265-6b5883a97e88)
BlueXP - Manual Installation without access keys.

This doesn't seem to be available and only:
BlueXP - Manual Installation exists now.

This should be updated to prevent confusion. Thanks.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Thank you @finnian345. I'll look into this and get it updated.

**Comment by netapp-bcammett** [comment]
The screenshot has been updated. Thanks again!
