### ISSUE TITLE
BlueXP Connector is installed in the cloud (in a government region, sovereign cloud region, or commercial region)

### ISSUE THREAD

**Issue by aattar4u** [NetAppDocs/bluexp-setup-admin#360]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html#overview

### Page title

Learn about BlueXP deployment modes

### Summary

When customer is deploying the BXP in restricted mode on commercial region, it give folowing error message,
![image](https://github.com/user-attachments/assets/3972d98e-ed06-4149-8156-5a295b79649c)

"Failed to create account credentialsShow Less
assume role validation failed . err: Error: assume role for arn:aws:iam::267552988247:role/DiscoverFSxOnNetAppONTAPRole failed . err: AccessDenied: User: arn:aws-us-gov:iam::033442085313:user/liraz is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::267552988247:role/DiscoverFSxOnNetAppONTAPRole"

When checkd with Liraz, got to know that restricted mode only supports to Gov cloud.
Since as per the DOC , customer has used commercial region (spain) which is giving above error.

Should we modify the DOC accoridngly? Or we need to support commercial region?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
No doc update needed at this time. Abdul is reaching out to the product team to determine if there's a bug or if a doc update is required. We'll open a new issue at that time.
