### ISSUE TITLE
Add DataLock to service and feature comparison table

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/bluexp-setup-admin#361]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html

### Page title

Learn about BlueXP deployment modes

### Summary

In this section: https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html#service-and-feature-comparison
We mention ransomware protection but we don't mention DataLock. DataLock is supported in all modes. We should add DataLock to the table so its clear that while ransomware protection is not supported in private/restricted, DataLock is supported.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Closing after discussing internally.
