### ISSUE TITLE
Add bullet to the page of the supported TLS versions of BlueXP Connector

### ISSUE THREAD

**Issue by virtualhawk** [NetAppDocs/bluexp-setup-admin#364]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-connector-default-config.html

### Page title

Default configuration for the Connector

### Summary

Azure has sent customer communications stating they are no longer supporting TLS 1.0/1.1 starting on October 31, 2024.  I was unable to find internal or external documentation stating which versions we support.  I have confirmed with BlueXP Engineering we use TLS 1.2.  Please reach out to me directly on teams @hawd and I can share the engineering contact that confirmed.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Discussing the update with David.

**Comment by virtualhawk** [comment]
Hi Ben,

                I received confirmation from BlueXP Engineering, "The Connector uses TLS 1.2 for all communication".  It is for all cloud providers, not just Azure.

David Hawkins
Cloud Solutions Architect, CVO Product Team
Mobile Phone: 330.892.7057
Need Help?  Please see our SharePoint<https://netapp.sharepoint.com/sites/CloudsolutionarchitectsGroup/SitePages/DetailedEngagementProcess.aspx>

**Comment by netapp-bcammett** [comment]
I added the details about Connector communication with cloud providers on the following page:
https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#communication-with-cloud-providers

Thanks again,
Ben
