### ISSUE TITLE
Add hop limit to 3 as a necessary configuration step for customers doing manual install of Connector in AWS

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/bluexp-setup-admin#370]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-manual.html

### Page title

Manually install the Connector in AWS

### Summary

Hi team, would be great to have the manual improved to add guidance for hop limit settings.

Majority of cases when customers create an EC2 instance they are going to use IMDSv2.
In that case, we need to modify hop limit to 3 for Connector to work.

Nowadays we have the guidance for hop limit in the IMDSv2 manual but we don't have it at the manual installation.

Please consider to add a section or a hint, etc at the "Step 1: Review host requirements" to indicate customer needs to review hop limit.

This is the manual for the hop limit:
https://docs.netapp.com/us-en/bluexp-setup-admin/task-require-imdsv2.html
(it is at step 1.c)

And this is the KB that the support team kindly created for your reference:
https://kb.netapp.com/Cloud/BlueXP/Cloud_Manager/Failed_to_Initialize_UI_after_manual_AWS_connector_installation

Regards,
Gabriel

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Gabriel,

I made the change as we discussed. Thanks again for reaching out and letting me know!

Regards,
Ben
