### ISSUE TITLE
Networking for computers accessing BlueXP

### ISSUE THREAD

**Issue by randobrando46** [NetAppDocs/bluexp-setup-admin#373]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html

### Page title

Install and set up a Connector on-premises

### Summary

In step 3 - we NEED to have a hyperlink to the requirements for any computers used to access BlueXP.  I'd suggest it be right under the very first sentence and with an added sentence.  "Any computer(s) or web-browser used to access the Connector and BlueXP will also need to have specific network endpoint access.  The requirements for computers can be found here:" maybe even do the link as "REQUIREMENTS FOR COMPUTERS THAT WILL ACCESS THE CONNECTOR OR BLUEXP" - maybe not all caps  :) - the link to that other doc is - https://docs.netapp.com/us-en/bluexp-setup-admin/reference-networking-saas-console.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Thank you for submitting this issue. I'm going to discuss further with the product team.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
This issue is being tracked internally through an engineering bug. We will make the required documentation updates after engineering completes the analysis.

See UMF-7855.

**Comment by netapp-bcammett** [comment]
Step 3 now includes a link to the endpoints that are contacted from a user's web browser.
https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html#step-3-set-up-networking

The page that lists the endpoints was also updated to mention the scenario related to setting up a Connector:
https://docs.netapp.com/us-en/bluexp-setup-admin/reference-networking-saas-console.html

Thanks,
Ben
