### ISSUE TITLE
To many "and then"

### ISSUE THREAD

**Issue by alonsod-netapp** [NetAppDocs/bluexp-setup-admin#386]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html

### Page title

Install and set up a Connector on-premises

### Summary

"and then" is repeated in last sentence of first paragraph.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Ah, good catch @alonsod-netapp! Thank you for pointing this out. I'm fixing it right now.
