### ISSUE TITLE
Japanese translation look and feel gets broken

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/bluexp-setup-admin#75]
Page: [Cloud Manager から Google Cloud でコネクタを作成します](https://docs.netapp.com/ja-jp/cloud-manager-setup-admin/task-creating-connectors-gcp.html)

When changing a page that contains icons and symbols to Japanese, its text formats, icon images, etc gets broken

English:
![image](https://user-images.githubusercontent.com/34706481/191636465-6802835a-72bc-461d-97f9-fb1bcd79c56d.png)

Japanese:
![image](https://user-images.githubusercontent.com/34706481/191636501-2de59274-ad4b-4767-ab5c-1fe70b323ecb.png)

I have seen this problem in all pages of the document that has similar formats.
Guessing this one may be complicated but if something could be done will improve Japanese readability.

Regards,
Gabriel

**Comment by netapp-bcammett** [comment]
@netapp-gudugunti,
This issue is related to localized content. However, I don't think there's a problem with the localized content itself. It's more about how it's being formatted, which could require a fix on the tooling side given that we're using specialized syntax in the adoc file to manipulate the CSS.

cc: @ntap-bmegan

**Comment by ntap-bmegan** [comment]
@netapp-gudugunti - I see the problem and am writing up a dev issue to fix it.

**Comment by gabrieltokyo** [comment]
Thank you! That looks better.

But I also see we still have issues in other parts:
English:
![image](https://user-images.githubusercontent.com/34706481/206062337-3ed57dd8-a58a-45d3-84ea-a41c6d7902db.png)

Japanese:
![image](https://user-images.githubusercontent.com/34706481/206062487-682af228-6b06-49a6-a24b-5d0647997999.png)
Note: The left side table format, last cell return codes and symbols and (not sure why but) the highlighted text does not exist in English.

Then, scrolling down, in the Create Connector section, if click on the gcloud tab, displayed contents are different.
Japanese version lacks of a portion of step3, step 4 and step 5

Regards,
Gabriel

**Comment by ntap-bmegan** [comment]
> Thank you! That looks better.

I'll let our developers know that they can close out on the issues around the quick start icons. 

> But I also see we still have issues in other parts: English: ![image](https://user-images.githubusercontent.com/34706481/206062337-3ed57dd8-a58a-45d3-84ea-a41c6d7902db.png)
> 
> Japanese: ![image](https://user-images.githubusercontent.com/34706481/206062487-682af228-6b06-49a6-a24b-5d0647997999.png) 
> 
> Note: The left side table format, last cell return codes and symbols and (not sure why but) the highlighted text does not exist in English.

I've checked the other languages and both problems - the slashes and hotlinks and the extra word - are unique to Japanese. 

> Then, scrolling down, in the Create Connector section, if click on the gcloud tab, displayed contents are different. Japanese version lacks of a portion of step3, step 4 and step 5

This is consistent across languages. 

I'll follow up on the additional items.

**Comment by netapp-gudugunti** [comment]
@gabrieltokyo and @ntap-bmegan, 
The problem has been resolved. Closing this issue.
