### ISSUE TITLE
More granular descriptions of permissions required for GCP

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/bluexp-setup-admin#78]
Page: [Google Cloud permissions for the Connector](https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-permissions-gcp.html)

A customer is requesting more granular information on why certain permissions are used on this page under the "How Google Cloud Permissions are Used" section.

Specifically for this section:
<img width="999" alt="image" src="https://user-images.githubusercontent.com/33675510/193049328-74e46355-2fea-4c3a-b899-fa9aa3b2a26d.png">

compute.networks.updatePolicy is mentioned without specifying exactly why this is needed for CVO HA deployment and is causing particular concern.

Additional for the "To Enable Cloud Data Sense" permissions details over why a "UseExternalIP" permissions are required.

**Comment by netapp-bcammett** [comment]
@mimitche,

Thank you for providing this feedback. I've reached out to the product team for more information.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
@mimitche,

In regards to the compute.networks.updatePolicy permission:

> It is needed to apply a firewall rule on the VPC/Subnet. We have different firewall rules for different VPCs.

I'll get that information added to the documentation. I'm digging a bit more on the other three permissions.

My apologies for the delay. Most of the product team has been out for holidays.

Regards,
Ben

**Comment by ntap-bmegan** [comment]
@netapp-bcammett - What is the status of this issue?

**Comment by netapp-bcammett** [comment]
We're waiting on input from the engineering team. I will update this issue when I have details to share.

**Comment by netapp-bcammett** [comment]
Mike,

There are no changes that we can make to the documentation at this time. Engineering analysis and subsequent updates to the BlueXP generated policy is required.

An issue is open with the engineering team to verify Google Cloud permissions for the Connector. We will update the documentation when the engineering work is complete. I can send you a link to this internal issue if you'd like.

Thanks,
Ben
